// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TwilioBridgeHostApi {
  func getLanguage() throws -> String
  func sendFromNative(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TwilioBridgeHostApiSetup {
  /// The codec used by TwilioBridgeHostApi.
  /// Sets up an instance of `TwilioBridgeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TwilioBridgeHostApi?) {
    let getLanguageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.getLanguage", binaryMessenger: binaryMessenger)
    if let api = api {
      getLanguageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLanguage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLanguageChannel.setMessageHandler(nil)
    }
    let sendFromNativeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.sendFromNative", binaryMessenger: binaryMessenger)
    if let api = api {
      sendFromNativeChannel.setMessageHandler { _, reply in
        api.sendFromNative() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      sendFromNativeChannel.setMessageHandler(nil)
    }
  }
}
