// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by PGNTwilioBridgeHostApi.
NSObject<FlutterMessageCodec> *PGNTwilioBridgeHostApiGetCodec(void);

@protocol PGNTwilioBridgeHostApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getLanguageWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)sendFromNativeWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpPGNTwilioBridgeHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNTwilioBridgeHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
