// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "HostAPIs.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation PGNMakeCallStatusBox
- (instancetype)initWithValue:(PGNMakeCallStatus)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

NSObject<FlutterMessageCodec> *PGNTwilioBridgeHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void SetUpPGNTwilioBridgeHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNTwilioBridgeHostApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.getLanguage"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getLanguageWithError:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(getLanguageWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getLanguageWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.sendFromNative"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendFromNativeWithCompletion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(sendFromNativeWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api sendFromNativeWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.initialize"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initializeWithCompletion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(initializeWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api initializeWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.deinitialize"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(deinitializeWithCompletion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(deinitializeWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api deinitializeWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.toggleAudioRoute"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(toggleAudioRouteToSpeaker:completion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(toggleAudioRouteToSpeaker:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        BOOL arg_toSpeaker = [GetNullableObjectAtIndex(args, 0) boolValue];
        [api toggleAudioRouteToSpeaker:arg_toSpeaker completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.makeCall"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(makeCallToken:completion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(makeCallToken:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_token = GetNullableObjectAtIndex(args, 0);
        [api makeCallToken:arg_token completion:^(PGNPGNMakeCallStatusBox *_Nullable enumValue, FlutterError *_Nullable error) {
          NSNumber *output = enumValue == nil ? nil : [NSNumber numberWithInteger:enumValue.value];
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.hangUp"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(hangUpWithCompletion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(hangUpWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api hangUpWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.muteUnmute"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(muteUnmuteWithCompletion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(muteUnmuteWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api muteUnmuteWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.twilio_sample.TwilioBridgeHostApi.changeAudioOutput"
        binaryMessenger:binaryMessenger
        codec:PGNTwilioBridgeHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(changeAudioOutputWithCompletion:)], @"PGNTwilioBridgeHostApi api (%@) doesn't respond to @selector(changeAudioOutputWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api changeAudioOutputWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
