package com.example.twilio_sample

object Constants {
    const val CALL_SID_KEY = "CALL_SID"
    const val VOICE_CHANNEL_LOW_IMPORTANCE = "notification-channel-low-importance"
    const val VOICE_CHANNEL_HIGH_IMPORTANCE = "notification-channel-high-importance"
    const val OUTGOING_CALL_RECIPIENT = "OUTGOING_CALL_RECIPIENT"
    const val INCOMING_CALL_INVITE = "INCOMING_CALL_INVITE"
    const val CANCELLED_CALL_INVITE = "CANCELLED_CALL_INVITE"
    const val INCOMING_CALL_NOTIFICATION_ID = "INCOMING_CALL_NOTIFICATION_ID"
    const val ACTION_ACCEPT = "ACTION_ACCEPT"
    const val ACTION_REJECT = "ACTION_REJECT"
    const val ACTION_INCOMING_CALL_NOTIFICATION = "ACTION_INCOMING_CALL_NOTIFICATION"
    const val ACTION_INCOMING_CALL = "ACTION_INCOMING_CALL"
    const val ACTION_OUTGOING_CALL = "ACTION_OUTGOING_CALL"
    const val ACTION_CANCEL_CALL = "ACTION_CANCEL_CALL"
    const val ACTION_FCM_TOKEN = "ACTION_FCM_TOKEN"
    const val accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzZlYmUwYTI3MGE2ODI5YmI1NmRiNmRlYTM2ZmU1N2RhLTE3MDQ3MjczMTciLCJncmFudHMiOnsiaWRlbnRpdHkiOiJTdW5ueUplbm92YVJhbGVpZ2giLCJ2b2ljZSI6eyJpbmNvbWluZyI6eyJhbGxvdyI6dHJ1ZX0sIm91dGdvaW5nIjp7ImFwcGxpY2F0aW9uX3NpZCI6IkFQNDZhNTk3ZjM1OGY4MzM3NTIxODJhMGU5YmExMzg4MDkifX19LCJpYXQiOjE3MDQ3MjczMTcsImV4cCI6MTcwNDczMDkxNywiaXNzIjoiU0s2ZWJlMGEyNzBhNjgyOWJiNTZkYjZkZWEzNmZlNTdkYSIsInN1YiI6IkFDMzhiZmYzZDk1ZDM0MjZkZTIyOWUzNmY5NDY5M2M3MTMifQ.QJY2dqXzp6CcjjjGD8Vp73l7gm7v8mbn7h4KWtmkuFM"
    const val OUTGOING_CALL_ADDRESS = "OUTGOING_CALL_ADDRESS"
    const val ACTION_DISCONNECT_CALL = "ACTION_DISCONNECT_CALL"
    const val ACTION_DTMF_SEND = "ACTION_DTMF_SEND"
}




