package com.example.twilio_sample

object Constants {
    const val CALL_SID_KEY = "CALL_SID"
    const val VOICE_CHANNEL_LOW_IMPORTANCE = "notification-channel-low-importance"
    const val VOICE_CHANNEL_HIGH_IMPORTANCE = "notification-channel-high-importance"
    const val OUTGOING_CALL_RECIPIENT = "OUTGOING_CALL_RECIPIENT"
    const val INCOMING_CALL_INVITE = "INCOMING_CALL_INVITE"
    const val CANCELLED_CALL_INVITE = "CANCELLED_CALL_INVITE"
    const val INCOMING_CALL_NOTIFICATION_ID = "INCOMING_CALL_NOTIFICATION_ID"
    const val ACTION_ACCEPT = "ACTION_ACCEPT"
    const val ACTION_REJECT = "ACTION_REJECT"
    const val ACTION_INCOMING_CALL_NOTIFICATION = "ACTION_INCOMING_CALL_NOTIFICATION"
    const val ACTION_INCOMING_CALL = "ACTION_INCOMING_CALL"
    const val ACTION_OUTGOING_CALL = "ACTION_OUTGOING_CALL"
    const val ACTION_CANCEL_CALL = "ACTION_CANCEL_CALL"
    const val ACTION_FCM_TOKEN = "ACTION_FCM_TOKEN"
    const val accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTS2Y5YTljN2U2NTBkMmFlOGI2ZTE4MGRjMzA4ZjliZWQ3LTE3MDkxMzU2ODgiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJDcmVhdGl2ZUdyYWNpZVdhcnNhdyIsInZvaWNlIjp7ImluY29taW5nIjp7ImFsbG93Ijp0cnVlfSwib3V0Z29pbmciOnsiYXBwbGljYXRpb25fc2lkIjoiQVBkY2I1OGJkODYyOGU2NzQwZmNkNWE3MDRjMGNkYTZiMSJ9fX0sImlhdCI6MTcwOTEzNTY4OCwiZXhwIjoxNzA5MTM5Mjg4LCJpc3MiOiJTS2Y5YTljN2U2NTBkMmFlOGI2ZTE4MGRjMzA4ZjliZWQ3Iiwic3ViIjoiQUMxZDQ3YjAzODU0ODRjZGYzODAxZWY3MzdiM2FiZmI3YSJ9.f4_PuE8SYCbViNnLX9tVmmwE3W6Vq3SsMSdwDb2n2gI"
    const val OUTGOING_CALL_ADDRESS = "OUTGOING_CALL_ADDRESS"
    const val ACTION_DISCONNECT_CALL = "ACTION_DISCONNECT_CALL"
    const val ACTION_DTMF_SEND = "ACTION_DTMF_SEND"
}




